/*
Problem Description:
The finance team wants to audit high-value customers who spent more on a single order than the total combined revenue generated by any item in the 'Beverages' category. 
Write an SQL query to pull the customer ID, full name, and email.
Use a subquery to find individual order amounts that surpass the maximum value computed from a nested correlated sum calculation of delivered beverage items,
and ensure the customer has never had a cancelled order by integrating an EXCEPT set operator clause.

case=1
output=
customer_id	full_name	email
1	Amit Sharma	amit.sharma@gmail.com
2	Priya Singh	priya.singh@yahoo.com
4	Neha Patel	neha.patel@yahoo.com
5	Arjun Gupta	arjun.gupta@gmail.com



*/
use fs;
SELECT c1.customer_id AS customer_id, CONCAT(c1.first_name," ",c1.last_name) AS full_name, c1.email As email
FROM Customers c1
WHERE c1.customer_ID IN (SELECT o.customer_id FROM Orders o WHERE o.total_amount > (SELECT MAX(o1.total_amount) FROM Orders o1 JOIN FoodItems f ON o1.food_id = f.food_id WHERE f.category = 'Beverages' AND o1.status = 'Delivered'))
AND c1.customer_ID IN(SELECT customer_id FROM Customers EXCEPT SELECT customer_id FROm Orders WHERE status = "Cancelled")
