/*
Problem Description:
The restaurant operations division wants to find out which food items are the primary revenue drivers within each menu section. 
Write a read-only SQL query that constructs a derived table to compute the total revenue generated by each food item 
(filtered only for orders that have been successfully 'Delivered'). 
Combine this with a correlated subquery to filter and return the food item name, category, and total revenue for the food items 
that have achieved the absolute highest revenue within their respective menu category.

case=1
output=
food_item_name	category	total_revenue
Masala Dosa	Breakfast	360.00
Chicken Biryani	Main Course	300.00
Dal Tadka	Main Course	300.00
Samosa	Snacks	270.00
Butter Naan	Breads	240.00
Mango Lassi	Beverages	180.00
Gulab Jamun	Desserts	150.00



*/
use fs;
SELECT revenue_data.food_item_name, revenue_data.category, revenue_data.total_revenue
FROM (
        SELECT f.name AS food_item_name, f.category, SUM(o.total_amount) AS total_revenue 
        FROM Orders o 
        JOIN FoodItems f
        ON o.food_id = f.food_id 
        WHERE status = 'Delivered'  
        GROUP BY f.food_id, f.name, f.category
) AS revenue_data

WHERE revenue_data.total_revenue = (
                                    SELECT MAX(inner_data.total_revenue) 
                                    FROM (
                                            SELECT f2.name, f2.category, SUM(o2.total_amount) AS total_revenue 
                                            FROM Orders o2 
                                            JOIN FoodItems f2 
                                            ON o2.food_id = f2.food_id 
                                            WHERE o2.status = 'Delivered' 
                                            GROUP BY f2.food_id, f2.name, f2.category
                                    ) AS inner_data 
                                    WHERE inner_data.category = revenue_data.category
)
ORDER BY revenue_data.total_revenue DESC;